### ISSUE TITLE
Error: Parse Error: missing field 'syncing'

### ISSUE THREAD

**Issue by stewfarq** [subspace/space-acres#121]
A few days ago whilst starting v.0.1.1 I get a consistent error, after the "Creating Consesus Node" screen, as follows :

**Error: Parse Error: missing field 'syncing'**

![Screenshot 2024-02-14 17 50 49](https://github.com/nazar-pc/space-acres/assets/119606349/61a85e07-83c6-4cd1-be0c-cd9da13855fe)

The node and farm was fully synced for about a week on the 3G network before this error.

**Comment by nazar-pc** [comment]
Do you happen to run another instance of Subspace software by any chance? Try to close the app and see in task manager if anything is running (or log out/log in just in case).

What this seems to indicate is that some other (older) version of Subspace might be running at the same time on the same machine.

**Comment by stewfarq** [comment]
Hi Nazar,  I have been running subspace on WSL (Ubuntu) on 3G network for about 8 weeks successfully in parallel.  They do not use the same SSD as I have two SSD's,  What is confusing me is that v0.1.1 was working for over a week with no changes in the config of the PC.  Do you recommend to try to reinstall v0.1.1?  How do I ensure that my 500Gb farm is not overwritten and is reused?

**Comment by nazar-pc** [comment]
Reinstallation will not change anything because I don't think installation is broken. Try to do what I suggested above and update me whether something changes.

**Comment by stewfarq** [comment]
Hi Nazar,  you are right.  I stopped my WSL Ubuntu node and farmer.  Started Space Acres and it started fine.  I then restarted the WSL farmer and got this error:


2024-02-14T20:09:53.208632Z  INFO subspace_farmer::commands::farm: Connecting to node RPC url=ws://127.0.0.1:9944
Error: Networking or low-level protocol error: Error when opening the TCP socket: Connection refused (os error 111)

Caused by:
    Error when opening the TCP socket: Connection refused (os error 111)

Is there a way to run both farmers in parallel?  e.g. to change the TCP port 9944 to another port?

**Comment by nazar-pc** [comment]
Interesting. Actually I wanted to change the port to avoid such overlap (and eventually we will disable RPC altogether), would you mind sending a PR changing default RPC port 9944 to 19944 here?: https://github.com/nazar-pc/space-acres/blob/16935f62db16fcaae5c16703a9da5a1ec524647f/src/backend/node.rs#L48

**Comment by nazar-pc** [comment]
Next release will fix this, thanks for reporting!
