### ISSUE TITLE
I want to create a Chinese version using the source code

### ISSUE THREAD

**Issue by qingyuhuaming** [subspace/space-acres#128]
I want to create a Chinese version using the source code
But after I changed part of the content in src\frontend to Chinese, the compiled installation package is still in English.
Can you tell me how to do it?
I'm not a programmer.

**Comment by nazar-pc** [comment]
You'll have to provide commands you ran to obtain new package.

CI does recompilation and packaging separately, you need to do recompilation for changes in `frontend` to be applied.

Also note that installing the same version on top of itself is not quite working properly for some reason (you will see Space Acres installed two or more times), make sure to remove it before installing again if you are installing the same version. There is no such issue with upgrades to newer version.

**Comment by nazar-pc** [comment]
https://github.com/subspace/space-acres/pull/129 fixes an issue of upgrade to the same version resulting in multiple installations.

**Comment by qingyuhuaming** [comment]
![image](https://github.com/subspace/space-acres/assets/59925193/1549c190-4ea6-4f4a-bc4b-c292a8407d8e)
I think I've succeeded
