### ISSUE TITLE
If the user incorrectly sets the size of the farm, it may lead to the error "Error: Can't preallocate plot file, probably not enough space on disk:" and there is no back button.

### ISSUE THREAD

**Issue by qingyuhuaming** [subspace/space-acres#130]
If the user incorrectly sets the size of the farm, it may lead to the error "Error: Can't preallocate plot file, probably not enough space on disk:" and there is no back button.

**Comment by nazar-pc** [comment]
This is a known UX issue, https://github.com/subspace/space-acres/issues/16 and https://github.com/subspace/space-acres/issues/115 are both meant to address this from different sides, please subscribe to those for updates
