### ISSUE TITLE
Add a readme with instructions on running SA in dev environment

### ISSUE THREAD

**Issue by EmilFattakhov** [subspace/space-acres#131]

**Comment by nazar-pc** [comment]
There is https://github.com/subspace/space-acres?tab=readme-ov-file#how-to-build, if you follow two provided links and do `cargo run` you should have an app up and running. What else do you expect to be in there?

**Comment by EmilFattakhov** [comment]
@nazar-pc sorry, this issue was not supposed to be here (it's at a private board, but I accidentally published it to SA). We can talk about it more tomorrow.
