### ISSUE TITLE
Some people's computers crash when opening this software.

### ISSUE THREAD

**Issue by qingyuhuaming** [subspace/space-acres#132]
Is it because their CPUs are too old and not compatible, requiring the compilation of a V2 version? How should this be done?

**Comment by nazar-pc** [comment]
I have never heard that computers crash when opening Space Acres. Space Acres may not open on old CPUs, but that is described in [Hardware requirements](https://github.com/subspace/space-acres/blob/main/docs/INSTALLATION.md#hardware-requirements) already.

You can compile the software for v2 yourself (including automatically in CI by modifying build target), but for now official builds are only for relatively modern processors.

**Comment by qingyuhuaming** [comment]
My meaning was indeed that the software would crash, not the computer; perhaps my expression was unclear. They indeed used some old CPUs. If I want to compile the V2 version, could you provide me with some general steps on how to operate? Because I am not a programmer, I can only try slowly.

**Comment by nazar-pc** [comment]
1. Fork repository
2. Change this line for Windows (and/or similar line above for Linux): https://github.com/subspace/space-acres/blob/main/.github/workflows/release.yml#L41
3. Go to "Actions" tab of the repository
4. Select "Release" workflow
5. Run workflow on the branch where you have made changes
6. Once workflow completes, you will see files attached in workflow results like here: https://github.com/subspace/space-acres/actions/runs/7966426258
