### ISSUE TITLE
[$100 USDC] Implement Tray icon support on Windows

### ISSUE THREAD

**Issue by EmilFattakhov** [subspace/space-acres#141]

**Comment by hunjixin** [comment]
which function tray icon need, just hide to try icon and click to show app page?

**Comment by hunjixin** [comment]
just do some investment with this issue,  other existing libraries do not support GTK4, for windows, it may be possible to implement the bind system call (https://github.com/rodrigocfd/winsafe/blob/b6337f6c6a145877f014de98f656141b60484f7c/src/shell/funcs.rs#L220),  but it will be more complicated for Linux(not know much). so i  want to confirm if it is necessary to use GTK3 to build this application?

翻译 我想确认这个应用是必须要使用gtk3来构建吗

**Comment by nazar-pc** [comment]
> so i want to confirm if it is necessary to use GTK3 to build this application?

I think you meant GTK4? If so then GTK4 doesn't have support for tray icon, meaning I have no idea how you'd use it.

The goal ultimately is to support tray icon, if you find a library that is not GTK-specific, it is still fine to use overall, but ideally we wouldn't call raw Windows APIs directly.

**Comment by hunjixin** [comment]
i think i can do archive close and open in windows in my early code.
