### ISSUE TITLE
[$100 USDC] Implement Tray icon support for Linux

### ISSUE THREAD

**Issue by EmilFattakhov** [subspace/space-acres#142]

**Comment by hunjixin** [comment]
@EmilFattakhov @nazar-pc  i think this work has beed done in pr https://github.com/subspace/space-acres/pull/172

ubuntu22.04

![image](https://github.com/subspace/space-acres/assets/41407352/901a81a3-d295-425d-865b-fa9a96c9e64b)

ubuntu 23.10

![image](https://github.com/subspace/space-acres/assets/41407352/ac4d9bee-88ed-4701-9d36-fb003c76dd8e)

kde neon 6.0

![image](https://github.com/subspace/space-acres/assets/41407352/679862b1-2a4f-423b-86bd-ab2d08c3657d)

**Comment by nazar-pc** [comment]
Agree, closing

**Comment by EmilFattakhov** [comment]
Thank you @hunjixin! Just as a reminder, please fill out [the compliance form](https://forms.gle/gtjavXSW6nF2wh216) to claim your reward! Looking forward to your future contributions!
