### ISSUE TITLE
Node name setting

### ISSUE THREAD

**Issue by RomanLabGit** [subspace/space-acres#160]
It is impossible to set a node name to enable telemetry server communication.

**Comment by nazar-pc** [comment]
Why do you need telemetry in the first place? What information is there that you need and don't see in the UI already?

**Comment by RomanLabGit** [comment]
It is useful for monitoring remote nodes. If the telemetry server is to be deprecated, Prometeus metrics will be a good alternative.

**Comment by nazar-pc** [comment]
Remote Space Acres nodes? That is not really the intended use case and metrics are disabled in Space Acres too. It is designed to be an easy to use desktop app.

**Comment by RomanLabGit** [comment]
Maybe you are right. But I saw several requests about that from the community members.

**Comment by nazar-pc** [comment]
Let me close for now then, but if there is a good use case we can add metrics endpoint. Telemetry though is not something users should be concerned with, it is more for us, developers, to see the size of the network, what OSs farmers use, etc.

**Comment by crow4586** [comment]
Yes, when I used NODE for a few hours, I found that my node could not be found in https://telemetry.subspace.network/, but the computer showed that everything was normal. After I switched to Acres, I found that I couldn't set the node name, so I couldn't see my node coming online. I just wanted to make sure that my node was normal and healthy. Others seemed to be able to set the node name in Acres, but I didn't find a way.

**Comment by nazar-pc** [comment]
> Others seemed to be able to set the node name in Acres, but I didn't find a way

There is no direct way as this issue indicates.

> I just wanted to make sure that my node was normal and healthy

There is no information in telemetry that says whether your node is normal and healthy. In fact there should be no useful information in telemetry that is not already shown in Space Acres UI. If there is something that you believe is missing, please request it specifically.
