### ISSUE TITLE
Debian unable to close Space Acres

### ISSUE THREAD

**Issue by mhstefanov** [subspace/space-acres#166]
It looks like closing the application via "x" button does not "kill" the application. The process stays on the background and you must kill it manually.

**Comment by nazar-pc** [comment]
Please post separate requests/issues separately, don't mix multiple unrelated things together.

**Comment by nazar-pc** [comment]
Do you have a screenshot of what application was doing at the time?

**Comment by mhstefanov** [comment]
@nazar-pc  OK I will separate the requests next time.

Yes sure, a screenshot is attached. Some details:
OS: Debian
CPU: i7-9700 (8 cores)
 
![subspace](https://github.com/subspace/space-acres/assets/163840115/5a5e5550-78f6-4f40-a8c0-06fe5fa1841f)

Closing the app does not kill the process:

![subspace2](https://github.com/subspace/space-acres/assets/163840115/62401caa-856b-4153-aabe-ec92550b5839)

and when you open the app again, the error msg says that it's already running.

**Comment by nazar-pc** [comment]
How long did you wait for it to exit?

**Comment by mhstefanov** [comment]
ahhh yeah... it's gone after 15-20sec. :)

**Comment by nazar-pc** [comment]
That is what I expected. It finishes some uninterruptible work and then goes away.

This is basically a duplicate of https://github.com/subspace/space-acres/issues/54, which when implemented will not close UI until farmer exits properly. Closing this as duplicate for now.
