### ISSUE TITLE
Farm errored and stopped

### ISSUE THREAD

**Issue by xli-cube** [subspace/space-acres#198]
![image](https://github.com/subspace/space-acres/assets/161856328/cf9c89c5-9099-4d88-90d6-f0ae9a674918)
Do I need to replace the hard drive again? Or redraw?

**Comment by nazar-pc** [comment]
Subspace doesn't support hard drives, only SSDs. And there is no "drawing" in Subspace, but there is "plotting", which I think is what you meant.

Search for "os error 23" online, it will help you undersand what it is and what to do about it. I'm quite certain replotting is not necessary and will not help here.

**Comment by xli-cube** [comment]
![image](https://github.com/subspace/space-acres/assets/161856328/afca409b-0810-45d2-b381-10bac950e24b)

**Comment by nazar-pc** [comment]
Not sure what that screenshot was supposed to mean. Don't think there is something to fix here necessarily, so will close it, but feel free to contnue discussion if you have something to add.
