### ISSUE TITLE
Links isn't working for MacOS package

### ISSUE THREAD

**Issue by DianaPertseva** [subspace/space-acres#213]
Hovering over icons/links is not working—text shows up for a second, making it impossible to read.

I will add a video explainer a bit later.

**Comment by nazar-pc** [comment]
I modified the issue to remove mention of icons. There is no official macOS package yet and once there is, icons will work there, it is a WIP packaging issue. Also please create separate issues for independent bugs, don't mix multiple together as it makes tracking harder.
