### ISSUE TITLE
Allow configuration edits during startup and when errors occur

### ISSUE THREAD

**Issue by skylordafk** [subspace/space-acres#218]
When space acres was offline I moved the db + network folders into a new directory. Then restarted the app to change the node's base path, but the app was stuck in "creating consensus node" mode which prevented me from updating the configuration (the option to edit wasn't available). I waited a few minutes before deciding to uninstall and reinstall space acres.

from nazar: "It is not just for loading though, when errors happen there is no way to edit configuration either IIRC."

It'd be nice if the option to edit config was always available, or there was another way to get rid of that uninstall/reinstall loop when farming configuration is changed outside of the app.

**Comment by nazar-pc** [comment]
I think this is very related to https://github.com/subspace/space-acres/issues/16, which once implemented will unlock all other use cases. There is subtle implementation trickiness, but definitely doable.
