### ISSUE TITLE
[$150 USDC] Packaging for macOS

### ISSUE THREAD

**Issue by nazar-pc** [subspace/space-acres#7]
The goal of the ticket is to package the application to MacOS. This should all run in CI just like Windows/Linux packaging does.

Couple of tools that might be useful to check out for inspiration:

- https://gitlab.gnome.org/GNOME/gtk-mac-bundler is probably an option to try.
- https://gitlab.freedesktop.org/dabrain34/GstPipelineStudio is a GTK4/GStreamer app packages for macOS that might be used as an example.

Installation through Brew is another possibility.

To earn the bounty, ensure your Pull Request (PR) is approved and merged by a Subspace team member. Remember to read [T&C](https://subspace.network/subspace-community-initiative-terms-and-conditions) before submitting your PR.

**Comment by RomanLabGit** [comment]
I'm currently researching MacOS packaging tools available for my commercial product. If I find one that is applicable to both commercial and public domain software, I can try to use it.  Does it have to be open-source?

**Comment by nazar-pc** [comment]
I think it either has to be open source or official tool from Apple, but let me know what you find.

I'll assign this issue to you for now, let me know if you abandon your attempts for whatever reason.

**Comment by jfrank-summit** [comment]
@RomanLabGit I'm curious if you have made any progress on this. Thanks!

**Comment by RomanLabGit** [comment]
I'm really sorry for the delay. I'm currently trying to get it compiled on my virtual Mojave macOS. Once it starts working, I should attempt to use `pkgbuild` and `productbuild` Xcode tools to build the package. That's my plan.

**Comment by nazar-pc** [comment]
Packaging for macOS was implemented in recent versions, closing
