### ISSUE TITLE
Predict when the next reward will be farmed

### ISSUE THREAD

**Issue by nazar-pc** [subspace/space-acres#86]
Since there is information on-chain about space pledged, by remembering when the next reward was received it should be possible to roughly predict when the next reward will be received. It would be nice to show it at least as high/low probability of receiving reward.

Something like "today", "in about an hour", "any time now".

**Comment by jim-counter** [comment]
In addition, could we have a SSC per hour metric based on the last x hours? Could be SSC per day? Could start with average over the last 24 hours?

Maybe this should be a separate issue as it's not predicting anything - the similarity is giving the user insight into performance.
